### ISSUE TITLE
Confusion with `gem 'capistrano-rvm'` (different gem ?)

### ISSUE THREAD

**Issue by petervandenabeele** [capistrano/rvm#11]
Hi,
/cc @mpapis
/cc @softr8

I may be confused, but these are my findings, trying to use this code with Capistrano v3.

Based on the `require 'capistrano/rvm'` in 

  https://github.com/capistrano/capistrano/blob/master/lib/capistrano/templates/Capfile#L18

and the link to documentation in 

https://github.com/capistrano/capistrano/blob/master/lib/capistrano/templates/Capfile#L11

and the gem.name of this project being 'capistrano-rvm':

https://github.com/capistrano/rvm/blob/master/capistrano-rvm.gemspec#L6

I went on to add to my Gemfile

`gem 'capistrano-rvm'`

However, it seems like that is a completely different gem, posted in July 2012 by Edwin Cruz ( @softr8 ):

http://rubygems.org/gems/capistrano-rvm

I presume, the source code for the 'capistrano-rvm' gem can be found here (I did not easily see that link on rubygems):

https://github.com/softr8/capistrano-rvm

The result of using the naive inclusion of the 'capistrano-rvm' gem is the predictable error:

```
cannot load such file -- capistrano/rvm
```

If there is no way to merge the 2 code bases, maybe this code (here) needs to adopt another gem.name and publish a gem under that name?

For now, what worked is to use the link to this code on github (of which I made a fork to be sure and with a more descriptive name).

```
  gem 'capistrano-rvm', github: "petervandenabeele/capistrano_rvm" # Clone a known working version
```

Maybe this code here could use the (somewhat ugly) github project name and gem.name of `capistrano_rvm` . One advantage would be that github clones would automatically inherit a name that is more different from the real `rvm` project and the project name and gem name would be in line.

Probably there are better alternatives, I was just a bit confused by this and trying to propose a solution. Better solutions are probably possible :-)

Thanks,

@petervandenabeele

**Comment by ayrton** [comment]
I believe this is the same 'issue' as with https://github.com/capistrano/rbenv, I simply used the `github:` syntax as stated in the readme.

**Comment by mpapis** [comment]
assuming the gem name is taken I would advise to just pick another one, or claim the one taken i it has no downloads, `github:` is not the best solution, not everybody wants to use `bundler`

**Comment by leehambley** [comment]
I'd propose to avoid namespace collisions we start to transition the plugin gems to be called "capistrano-plugin-rbenv" - but it's just an ugly workaround.

**Comment by leehambley** [comment]
Perhaps better to address this now than before the naming propagates as-is.

**Comment by petervandenabeele** [comment]
Hi Edwin ( @softr8 ),

Any ideas on this ?

@petervandenabeele

**Comment by softr8** [comment]
oh no!

Is there any way to transfer the ownership? I'm big fan/user of capistrano and whatever is better for the project I'm wiling to accept it.

**Comment by petervandenabeele** [comment]
Thanks  :-)

**Comment by mpapis** [comment]
@softr8 `gem help owner`

**Comment by softr8** [comment]
I've added @kirs as owner

**Comment by leehambley** [comment]
Thanks for the epic teamwork here gents!

## Lee Hambley

http://lee.hambley.name/
+49 (0) 170 298 5667

**Comment by kirs** [comment]
Thanks! I've pushed it on rubygems and mentioned it in README.
