### ISSUE TITLE
Check that :application is set.

### ISSUE THREAD

**Issue by jcoyne** [capistrano/rvm#14]
If it isn't set, it attempts to produce a wrapper like this:

`INFO [689ab449] Running /usr/local/rvm/bin/rvm wrapper ruby-2.0.0-p247  bundle gem rake ruby on sandbox`

rather than:
`INFO [689ab449] Running /usr/local/rvm/bin/rvm wrapper ruby-2.0.0-p247 my_app bundle gem rake ruby on sandbox`

It would be better to raise an exception saying you must set application, or provide a default.

**Comment by mpapis** [comment]
I already mentioned in https://github.com/capistrano/rvm/issues/13#issuecomment-26431685 that `wrappers` dir should be used instead of `bin` and then it should be possible to skip the application name

**Comment by jcoyne** [comment]
@mpapis It was unclear that the solution for #13 would apply to the problem I have.

**Comment by mpapis** [comment]
it should be possible to make it simpler, I will play with it tomorrow and open a PR if it works (should fix both issues)

**Comment by kirs** [comment]
@jcoyne could you try [this](https://github.com/capistrano/rvm/pull/16) fork?

**Comment by jcoyne** [comment]
Didn't work for me.

```
cap sandbox deploy
...
 INFO [eea5772e] Running /usr/local/rvm/bin/rvm wrapper ruby-2.0.0-p247  bundle gem rake ruby on sandbox
DEBUG [eea5772e] Command: /usr/local/rvm/bin/rvm wrapper ruby-2.0.0-p247  bundle gem rake ruby
DEBUG [eea5772e]    Saving wrappers to '/usr/local/rvm/bin'
DEBUG [eea5772e]    .
DEBUG [eea5772e]    .
DEBUG [eea5772e]    .
DEBUG [eea5772e]    
...

```

**Comment by jcoyne** [comment]
Oh, I think this was my fault. It does work when I `bundle exec cap ...`
