### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by cschramm** [capistrano/rvm#15]
The gem seems to miss any license information.

**Comment by leehambley** [comment]
@kirs not sure if you caught the pull request on Capistrano, but there was a license screw up over there, we were saying it was CC by nc sa, but it had the GPL in the license file. Tom and I settled on the MIT licence, and 3.1 will be released under that licence.

**Comment by kirs** [comment]
Done: https://github.com/capistrano/rvm/blob/master/LICENSE.txt

**Comment by cschramm** [comment]
Woah, faster than light. :+1:
