### ISSUE TITLE
rvm:hook requirement outside deploy process

### ISSUE THREAD

**Issue by aackerman** [capistrano/rvm#19]
It seems to me, to be troublesome to impose using the `rvm:hook` task on every other library that wants to work in tandem. I contribute to the [`sidekiq`](https://github.com/mperham/sidekiq) project, and this would require us to make a change for the two libraries to work together.

For instance, on a fresh install of rails, with capistrano v3, and capistrano/rvm, and sidekiq. Running `cap production sidekiq:start` will simply not work unless a change was made, either by the host app or the sidekiq project to call `rvm:hook` before the sidekiq tasks ran.

**Comment by Kriechi** [comment]
Should be solved now - because of #22 adds the hook to every stage.

**Comment by kirs** [comment]
Yeah, I've already released the `0.1.0` :smirk:
