### ISSUE TITLE
rvm_path vs rvm_custom_path

### ISSUE THREAD

**Issue by kyledecot** [capistrano/rvm#23]
I'm a little confused as to why there is both `rvm_path` and `rvm_custom_path`. What is the difference between the two?

**Comment by Kriechi** [comment]
The only relevant one for the user is `:rvm_custom_path`
The other one is just used internally during run time.

**Comment by kyledecot** [comment]
If `rvm_path` is only meant to be used internally then shouldn't it be an instance method or something. It seems that leveraging capistrano's `set` method leads people to assume that this is supposed to be a configurable value.

**Comment by Kriechi** [comment]
Valid point.
But maybe people should only assume things to use, which are documented in the README.
If someone really wants to go through the code, I would assume the person will figure it out.

just my 2 cents.

**Comment by mczepiel** [comment]
FWIW, the README currently mentions `:rvm_custom_path` as the way to specify the path but setting that has no effect on `capistrano/bundler`'s `bundle:install` task Meanwhile, setting `:rvm_path` gets things pointed at the right place.

There are plenty of contradictory examples/docs out there; it's not obvious what you're supposed to actually do.

**Comment by cklll** [comment]
+1 for @mczepiel 
```
which rvm
/usr/local/rvm/bin/rvm
```

And then the following `deploy.rb` works
```
set :rvm_type, :system
set :rvm_path, '/usr/local/rvm'
```
