### ISSUE TITLE
why not invoke rvm:init by default?

### ISSUE THREAD

**Issue by blankyao** [capistrano/rvm#24]
In my opinion, there should be only one specific version of ruby within a project, so why not invoke **rvm:init** by default to invoke all the tasks with the same version of ruby?

**Comment by leehambley** [comment]
That's not how capistrano works. Each execute() happens in its own SSH
channel. Please close this question. This is a bug tracker, not
stackoverflow!

**Comment by blankyao** [comment]
ok, thanks.
