### ISSUE TITLE
using --dry-run causes error

### ISSUE THREAD

**Issue by jondruse** [capistrano/rvm#30]
$ cap staging deploy --dry-run 

produces this error.

<pre>
undefined method `verbosity' for "~/.rvm/bin/rvm version\n":String
/Users/jondruse/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.2.0/lib/sshkit/formatters/pretty.rb:10:in `write'
/Users/jondruse/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.2.0/lib/sshkit/backends/printer.rb:14:in `block in execute'
/Users/jondruse/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.2.0/lib/sshkit/backends/printer.rb:13:in `tap'
/Users/jondruse/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.2.0/lib/sshkit/backends/printer.rb:13:in `execute'
/Users/jondruse/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.2.0/lib/sshkit/backends/printer.rb:23:in `block in capture'
/Users/jondruse/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.2.0/lib/sshkit/backends/printer.rb:23:in `tap'
/Users/jondruse/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.2.0/lib/sshkit/backends/printer.rb:23:in `capture'
/Users/jondruse/.rvm/gems/ruby-2.0.0-p247/gems/capistrano-rvm-0.1.0/lib/capistrano/tasks/rvm.rake:8:in `block (3 levels) in <top (required)>'
/Users/jondruse/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.2.0/lib/sshkit/backends/printer.rb:9:in `instance_exec'
/Users/jondruse/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.2.0/lib/sshkit/backends/printer.rb:9:in `run'
/Users/jondruse/.rvm/gems/ruby-2.0.0-p247/gems/sshkit-1.2.0/lib/sshkit/runners/parallel.rb:12:in `block (2 levels) in execute'
Tasks: TOP => rvm:check

</pre>

**Comment by kirs** [comment]
The problem is that `dry run` is not possible in the current Capistrano workflow. It's not a `capistran-rvm` issue.

You can read more here: https://github.com/capistrano/sshkit/issues/39
