### ISSUE TITLE
Remove SSHKit dependency

### ISSUE THREAD

**Issue by Kriechi** [capistrano/rvm#31]
capistrano-rvm blocks the usage of a newer SSHKit gem version, because of the over restrictive version selector.

I think we should remove the SSHKit dependency completely.

**Comment by mpapis** [comment]
I would change it to `>=` as it was required for the prefix on command map

**Comment by Kriechi** [comment]
Good catch. Thanks. I didn't think about the command map.
Of course, then i would suggest using `>=1.2`.

**Comment by kirs** [comment]
We have SSHKit dependency because it's used inside the capistrano-rbenv code: https://github.com/capistrano/rvm/blob/master/lib/capistrano/tasks/rvm.rake#L35

It's important to have >=1.2 because we need exact features from this version.

> capistrano-rvm blocks the usage of a newer SSHKit gem version, because of the over restrictive version selector.
> that means we just have to use flexible dependency, right?

**Comment by kirs** [comment]
Fixed: https://github.com/capistrano/rvm/blob/master/capistrano-rvm.gemspec

**Comment by mpapis** [comment]
I still see:

``` ruby
gem.add_dependency 'sshkit', '~> 1.2'
```

was it supposed to be `>=`?

**Comment by kirs** [comment]
It wasn't, because `>=` would allow to use 2.x that may have breaking API changes.

**Comment by mpapis** [comment]
then I'm confused, `1.2` introduced that breaking changes, it should be pushed to `2.0` then ... just saying
