### ISSUE TITLE
capistrano-rvm and capistrano-rails cant find bundle

### ISSUE THREAD

**Issue by magpieuk** [capistrano/rvm#32]
Had a problem today when trying to deploy using capistrano and rvm. 

rvm is system based.

When the capistrano was trying to use rake to precompile assets the system complained about not being able to find bundle. Previously in the deploy command had run successfully. I noticed that this command was run with "/usr/local/rvm/bin/rvm ruby-2.0.0-p353 do" while the rake task to do the precompile was "RAILS_ENV=staging bundle exec rake assets:precompile"

putting the following into the deploy.rb sorted it out <code>SSHKit.config.command_map.prefix[:rake].unshift("/usr/local/rvm/bin/rvm ruby-2.0.0-p353 do")</code> worked but as far as I could tell the capistrano-rvm should have already done this. Any ideas?

**Comment by Kriechi** [comment]
Are you using the latest gem versions pubished on rubygems?
Could you please gist your Capfile and deploy.rb?

**Comment by magpieuk** [comment]
https://gist.github.com/magpieuk/8111697

Any hints on how to debug this would be great.

**Comment by Kriechi** [comment]
Your capistrano-rvm gem version is not up2date.

0.1.0 is the latest one, which should work better with capistrano-bundler, specifically fixing the issue you are experiencing.

**Comment by magpieuk** [comment]
Ah many thanks. Missed that I did not have the latest version, bundle update capistrano-rvm had not picked up the new version. will give it a go. Cheers!

**Comment by magpieuk** [comment]
Yep that sorted it. Thanks for assistance.
