### ISSUE TITLE
Support for capistrano 3.1.0?

### ISSUE THREAD

**Issue by adamlwatson** [capistrano/rvm#44]
Just wondering if this is in the works, and if so, what kind of ETA there might be.

Thanks!

**Comment by kirs** [comment]
What do you mean?
capistrano-rvm is capable with capistano >=3.0

**Comment by adamlwatson** [comment]
Well, yesterday I was getting bundler dependency errors when I tried to update cap to 3.1.0. Today, however, the update worked.

Thanks for the reply.
