### ISSUE TITLE
cannot load such file -- capistrano/rvm

### ISSUE THREAD

**Issue by nesrual** [capistrano/rvm#5]
I get the following error when using capistrano-rvm:

```
cap aborted!
cannot load such file -- capistrano/rvm
```

My Gemfile contains the following entries:

```
gem 'capistrano', :github => 'capistrano/capistrano', :branch => 'v3'
gem 'capistrano-rvm', github: 'capistrano/rvm'
```

And the Gemfile.lock:

```
GIT
  remote: git://github.com/capistrano/capistrano.git
  revision: 5f3a2b67ff506dedbd92c9c7e59010fa360d1f12
  branch: v3
  specs:
    capistrano (3.0.0.pre14)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 0.0.23)

GIT
  remote: git://github.com/capistrano/rvm.git
  revision: 76d7cd6bd86430210d7eb8cbc209f4b5161c42a2
  specs:
    capistrano-rvm (0.0.1)
      capistrano
```

I am using rvm 1.22.3 (master) under OSX. Ruby version is ruby-2.0.0-p247

**Comment by kirs** [comment]
Do you use `bundle exec` before the `cap` command?

**Comment by nesrual** [comment]
That did the trick - sorry. Problem solved.

**Comment by kirs** [comment]
That's because your default binstub of `cap` points to capistrano 2.x.
You can generate binstubs in the app directory and add ./bin to $PATH, after that you won't need to type `bundle exec` each time.

## 

Kir Shatrov
+7 (929) 631-46-35

**Comment by tthommmm** [comment]
gf
