### ISSUE TITLE
Add rvm:install

### ISSUE THREAD

**Issue by emirkin** [capistrano/rvm#50]
It would be nice to have an rvm-install task to install rvm+ruby

**Comment by mpapis** [comment]
please look into https://github.com/capistrano/rvm/pull/34 - https://github.com/rvm/rvm1-capistrano3 contains the install task and after merge you could use it ... or just use rvm1-capistrano3

**Comment by emirkin** [comment]
Oh cool. Is it going to become part of capistrano/rvm at some point?

**Comment by mpapis** [comment]
maybe if more people ask for it, right now authors of this gem (`capistrano/rvm`) are not sure they want allow any of `rvm/rvm1-capistrano3` to be merged, they do not agree either with the core how it works neither with the additions like installing RVM or rubies.

**Comment by mpapis** [comment]
can this be closed as rejected?

**Comment by mpapis** [comment]
@kirs could you close this one please?

**Comment by kirs** [comment]
Thanks, I believe it's now fixed in README https://github.com/capistrano/rvm/commit/805d76b30443ff7f62a64d8e69fda22e29cb5765
