### ISSUE TITLE
How to execute rvm trust?

### ISSUE THREAD

**Issue by Rodrigora** [capistrano/rvm#51]
I added this question to StackOverflow asking [How to run rvmrc trust command using Capistrano 3](http://stackoverflow.com/questions/23544739/how-to-run-rvmrc-trust-command-using-capistrano-3)?

Why this task is not part of this gem?

**Comment by BillyParadise** [comment]
+1 Would love to know. Battling it now.

**Comment by cassioscabral** [comment]
Would like to know how to do that also

**Comment by chrisbloom7** [comment]
+1

**Comment by kirs** [comment]
Do you use .rvmrc to set the ruby version?

**Comment by chrisbloom7** [comment]
Well, I was... 

Switched to using `.ruby-version` and `.ruby-gemset` and problem is gone. Hurray for best practices!

**Comment by kirs** [comment]
Basically, .rvmrc tasks are not part of this gem because ruby version is set with `rvm_ruby_version` option in `deploy.rb`:

``` ruby
set :rvm_ruby_version, '2.0.0-p247'
```

**Comment by chrisbloom7** [comment]
@kirs That makes sense since this gem is just a wrapper to execute Capistrano commands in the proper context. Thanks.
