### ISSUE TITLE
Release v0.1.2 on rubygems

### ISSUE THREAD

**Issue by pangratz** [capistrano/rvm#52]
The `rvm_roles` property introduced in #41 is a useful feature, can you release a version `0.1.2` on rubygems?

**Comment by wursttheke** [comment]
+1 for me! Need this feature because we have machines not running rvm. Please do a quick :ship: :)

**Comment by betesh** [comment]
+1

**Comment by danlopez** [comment]
+1

**Comment by pangratz** [comment]
Now with #42 being merged, a new release would be even more awesome :wink:

**Comment by kirs** [comment]
Done!

**Comment by pangratz** [comment]
@kirs :100: :+1:
