### ISSUE TITLE
Add rvmsudo to default rvm_map_bins

### ISSUE THREAD

**Issue by RKushnir** [capistrano/rvm#53]
Please, consider adding `rvmsudo` to the list of binaries that get an `/usr/local/rvm ... do`  prefix(`rvm_map_bins`). My specific use case is with foreman:

```
execute :rvmsudo, :foreman, "export", "upstart"
```

Without the prefix it just says `/usr/bin/env: rvmsudo: No such file or directory`.

**Comment by jlhervo** [comment]
Just add `set :rvm_map_bins, %w{gem rake ruby bundle rvmsudo}` to your `deploy.rb` file and it should work.

**Comment by RKushnir** [comment]
@jlhervo Thanks, that's what I did until the issue is resolved.

**Comment by nisanthchunduru** [comment]
Better, add it to existing list of bins in deploy.rb

``` ruby
set :rvm_map_bins, fetch(:rvm_map_bins, []).push('rvmsudo')
```

**Comment by RKushnir** [comment]
I discovered, if foreman is installed in the system ruby, there's no need to use `rvmsudo`, as the regular `sudo` works.
