### ISSUE TITLE
rvm current/ default does not respect .ruby-version

### ISSUE THREAD

**Issue by gucki** [capistrano/rvm#59]
The task should first change to the current/ release folder so a possibly existing `.ruby-version` file gets picked up by RVM. Otherwise `current` or `default` report the system default, not the one specified in the `.ruby-version` file.

**Comment by gucki** [comment]
Pull request is here now: https://github.com/capistrano/rvm/pull/60

**Comment by thbar** [comment]
@gucki I think it's worth re-opening this, because the PR has never been merged and your issue still applies. Today I used a quick fix which works nicely:

```ruby
set :rvm_ruby_version, IO.read('.ruby-version')
```
