### ISSUE TITLE
Net::SSH::AuthenticationFailed in Execute rvm:hook

### ISSUE THREAD

**Issue by raidiant** [capistrano/rvm#80]
When executing `cap production deploy:initial` cap aborts in rvm:hook with the error:
_Net::SSH::AuthenticationFailed: Authentication failed for user user@ipaddress_
Where user is the deploy user and ipaddress is the ip of my server.

Logging into the server as the user via ssh works.

**Comment by hieunguyentrung** [comment]
I have this issue too. Did you fix it? Please help me.

**Comment by raidiant** [comment]
I tried debugging NetSSH but I don't seem to get any further. That, and I've just been on holiday. But I'll try to look into it further this week

**Comment by hieunguyentrung** [comment]
@raidiant I followed this guild and it works.
https://www.sitepoint.com/deploy-your-rails-app-to-aws/

**Comment by raidiant** [comment]
Fixed it:

You have to add your ssh key to the ssh agent by running `ssh-add ~/.ssh/id_rsa` or if your ssh key is located somewhere else replace the path with the path to your ssh key.
And verify by running `ssh-add -l`
After this every `cap` command should work as expected.

**Comment by abudevops** [comment]
top
