### ISSUE TITLE
install rvm/rubies

### ISSUE THREAD

**Issue by mpapis** [capistrano/rvm#9]
Hi I'm interested in maintenance of this extensions and adding installation of rvm and rubies to it, should I open PR or better to extract this things to separate gem(s)?

**Comment by Kriechi** [comment]
I suggest starting with a PR is a good call.
Then let's see what happens.

What additional functionality do you have in mind.
The whole capistrano-rails + capistrano-bundler + capistrano-{rbenv,rvm} is still under development/experimenting of some kind.

**Comment by mpapis** [comment]
I guess most of [rvm/capistrano](https://github.com/wayneeseguin/rvm-capistrano), but I would start with adding tasks to:
- install rvm
- install ruby
- create gemset (should be called by default)

**Comment by kirs** [comment]
Sorry, but capistrano/rvm is just about command wrappers. It's not capistrano' responsibility to install rubies or gemsets. You can use Chef or Puppet for that.

**Comment by leehambley** [comment]
Agreed @kirs, installing Rubies/etc is the responsibility of (possibly some other Capistrano v3 tasks, in another Gem, inspired by this one) or by a tool such as Chef/Puppet/Salt, etc.

We want to keep Capistrano to be an imperative deploy time tool, for provisioning there are better tools than imperative command wrappers that are better dependency driven and better suited to the task. For an example of driving Chef solo very simply with Cap3 see [this blog article](http://lee.hambley.name/2013/06/11/using-capistrano-v3-with-chef.html).

**Comment by mpapis** [comment]
I was just following https://github.com/capistrano/rvm#restrictions ... 

I do not believe those "big" tools suite everybody, there is still place for simple things to be done, for users just starting or maintaining only one server.

I have most of the code already written in `rvm-capistrano` but as there is already this gem(`capistrano-rvm`) which deprecates the core of `rvm-capistrano` I was thinking I can get the code working here - at first I was considering `capistrano/rvm-manage` to separate the installation so it's not turned on by default, but then read the message https://github.com/capistrano/rvm#restrictions and thought it's the intent to do that.

Anyway - I will work on this, just thought it will be a lot easier for users to require one extension instead of two to manage their tool - also part of the deploy is to create gemset - which should be done in here, otherwise users will fast start writing their own code to do that.
